<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="20" passed="8" failed="12" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2017-12-16T10:37:12Z" name="Sequential" finished-at="2017-12-16T10:37:16Z" duration-ms="3827">
    <groups>
      <group name="group2">
        <method signature="HttpBinRedirectTest.testResponseHeadersDefault()[pri:0, instance:Httpbin.HttpBinRedirectTest@694abbdc]" name="testResponseHeadersDefault" class="Httpbin.HttpBinRedirectTest"/>
        <method signature="HttpBinRedirectTest.testResponseHeadersInParameters1()[pri:0, instance:Httpbin.HttpBinRedirectTest@694abbdc]" name="testResponseHeadersInParameters1" class="Httpbin.HttpBinRedirectTest"/>
        <method signature="HttpBinRedirectTest.testResponseHeadersInParameters2()[pri:0, instance:Httpbin.HttpBinRedirectTest@694abbdc]" name="testResponseHeadersInParameters2" class="Httpbin.HttpBinRedirectTest"/>
        <method signature="HttpBinRedirectTest.testResponseHeadersInParameters3()[pri:0, instance:Httpbin.HttpBinRedirectTest@694abbdc]" name="testResponseHeadersInParameters3" class="Httpbin.HttpBinRedirectTest"/>
        <method signature="HttpBinRedirectTest.testResponseHeadersInParameters4()[pri:0, instance:Httpbin.HttpBinRedirectTest@694abbdc]" name="testResponseHeadersInParameters4" class="Httpbin.HttpBinRedirectTest"/>
      </group> <!-- group2 -->
      <group name="group1">
        <method signature="HttpBinHeadersTest.testGetArgs1()[pri:0, instance:Httpbin.HttpBinHeadersTest@6e20b53a]" name="testGetArgs1" class="Httpbin.HttpBinHeadersTest"/>
        <method signature="HttpBinHeadersTest.testGetArgs2()[pri:0, instance:Httpbin.HttpBinHeadersTest@6e20b53a]" name="testGetArgs2" class="Httpbin.HttpBinHeadersTest"/>
        <method signature="HttpBinHeadersTest.testGetArgs3()[pri:0, instance:Httpbin.HttpBinHeadersTest@6e20b53a]" name="testGetArgs3" class="Httpbin.HttpBinHeadersTest"/>
        <method signature="HttpBinHeadersTest.testGetArgs4()[pri:0, instance:Httpbin.HttpBinHeadersTest@6e20b53a]" name="testGetArgs4" class="Httpbin.HttpBinHeadersTest"/>
        <method signature="HttpBinHeadersTest.testGetDefaultBodyResponse()[pri:0, instance:Httpbin.HttpBinHeadersTest@6e20b53a]" name="testGetDefaultBodyResponse" class="Httpbin.HttpBinHeadersTest"/>
        <method signature="HttpBinHeadersTest.testGetHeaders()[pri:0, instance:Httpbin.HttpBinHeadersTest@6e20b53a]" name="testGetHeaders" class="Httpbin.HttpBinHeadersTest"/>
        <method signature="HttpBinHeadersTest.testGetInvalidMethod()[pri:0, instance:Httpbin.HttpBinHeadersTest@6e20b53a]" name="testGetInvalidMethod" class="Httpbin.HttpBinHeadersTest"/>
        <method signature="HttpBinHeadersTest.testGetInvalidUrl()[pri:0, instance:Httpbin.HttpBinHeadersTest@6e20b53a]" name="testGetInvalidUrl" class="Httpbin.HttpBinHeadersTest"/>
        <method signature="HttpBinRedirectTest.testResponseHeadersInvalidMethod()[pri:0, instance:Httpbin.HttpBinRedirectTest@694abbdc]" name="testResponseHeadersInvalidMethod" class="Httpbin.HttpBinRedirectTest"/>
        <method signature="HttpBinStatusCodeTest.testPostArgs()[pri:0, instance:Httpbin.HttpBinStatusCodeTest@2e005c4b]" name="testPostArgs" class="Httpbin.HttpBinStatusCodeTest"/>
        <method signature="HttpBinStatusCodeTest.testPostDefaultBodyResponse()[pri:0, instance:Httpbin.HttpBinStatusCodeTest@2e005c4b]" name="testPostDefaultBodyResponse" class="Httpbin.HttpBinStatusCodeTest"/>
        <method signature="HttpBinStatusCodeTest.testPostInvalidMethod()[pri:0, instance:Httpbin.HttpBinStatusCodeTest@2e005c4b]" name="testPostInvalidMethod" class="Httpbin.HttpBinStatusCodeTest"/>
        <method signature="HttpBinStatusCodeTest.testPostJson1()[pri:0, instance:Httpbin.HttpBinStatusCodeTest@2e005c4b]" name="testPostJson1" class="Httpbin.HttpBinStatusCodeTest"/>
        <method signature="HttpBinStatusCodeTest.testPostJson2()[pri:0, instance:Httpbin.HttpBinStatusCodeTest@2e005c4b]" name="testPostJson2" class="Httpbin.HttpBinStatusCodeTest"/>
        <method signature="HttpBinStatusCodeTest.testPostJson3()[pri:0, instance:Httpbin.HttpBinStatusCodeTest@2e005c4b]" name="testPostJson3" class="Httpbin.HttpBinStatusCodeTest"/>
      </group> <!-- group1 -->
    </groups>
    <test started-at="2017-12-16T10:37:12Z" name="Sequential tests" finished-at="2017-12-16T10:37:16Z" duration-ms="3827">
      <class name="Httpbin.HttpBinRedirectTest">
        <test-method signature="testResponseHeadersDefault()[pri:0, instance:Httpbin.HttpBinRedirectTest@694abbdc]" started-at="2017-12-16T13:37:15Z" name="testResponseHeadersDefault" finished-at="2017-12-16T13:37:16Z" duration-ms="134" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[Header - Server] expected:
<'nginx'>
 but was:
<'meinheld/0.6.1'>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [Header - Server] expected:
<'nginx'>
 but was:
<'meinheld/0.6.1'>
	at Httpbin.HttpBinRedirectTest.testResponseHeadersDefault(HttpBinRedirectTest.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResponseHeadersDefault -->
        <test-method signature="testResponseHeadersInParameters1()[pri:0, instance:Httpbin.HttpBinRedirectTest@694abbdc]" started-at="2017-12-16T13:37:16Z" name="testResponseHeadersInParameters1" finished-at="2017-12-16T13:37:16Z" duration-ms="135" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[Header - Server] expected:
<'nginx'>
 but was:
<'meinheld/0.6.1'>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [Header - Server] expected:
<'nginx'>
 but was:
<'meinheld/0.6.1'>
	at Httpbin.HttpBinRedirectTest.testResponseHeadersInParameters1(HttpBinRedirectTest.java:87)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResponseHeadersInParameters1 -->
        <test-method signature="testResponseHeadersInParameters2()[pri:0, instance:Httpbin.HttpBinRedirectTest@694abbdc]" started-at="2017-12-16T13:37:16Z" name="testResponseHeadersInParameters2" finished-at="2017-12-16T13:37:16Z" duration-ms="135" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Httpbin.HttpBinRedirectTest.testResponseHeadersInParameters2(HttpBinRedirectTest.java:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResponseHeadersInParameters2 -->
        <test-method signature="testResponseHeadersInParameters3()[pri:0, instance:Httpbin.HttpBinRedirectTest@694abbdc]" started-at="2017-12-16T13:37:16Z" name="testResponseHeadersInParameters3" finished-at="2017-12-16T13:37:16Z" duration-ms="135" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Httpbin.HttpBinRedirectTest.testResponseHeadersInParameters3(HttpBinRedirectTest.java:158)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResponseHeadersInParameters3 -->
        <test-method signature="testResponseHeadersInParameters4()[pri:0, instance:Httpbin.HttpBinRedirectTest@694abbdc]" started-at="2017-12-16T13:37:16Z" name="testResponseHeadersInParameters4" finished-at="2017-12-16T13:37:16Z" duration-ms="135" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Httpbin.HttpBinRedirectTest.testResponseHeadersInParameters4(HttpBinRedirectTest.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResponseHeadersInParameters4 -->
        <test-method signature="testResponseHeadersInvalidMethod()[pri:0, instance:Httpbin.HttpBinRedirectTest@694abbdc]" started-at="2017-12-16T13:37:16Z" name="testResponseHeadersInvalidMethod" finished-at="2017-12-16T13:37:16Z" duration-ms="136" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[Response code] expected:
<405>
 but was:
<200>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [Response code] expected:
<405>
 but was:
<200>
	at Httpbin.HttpBinRedirectTest.testResponseHeadersInvalidMethod(HttpBinRedirectTest.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testResponseHeadersInvalidMethod -->
      </class> <!-- Httpbin.HttpBinRedirectTest -->
      <class name="Httpbin.HttpBinStatusCodeTest">
        <test-method signature="testPostArgs()[pri:0, instance:Httpbin.HttpBinStatusCodeTest@2e005c4b]" started-at="2017-12-16T13:37:14Z" name="testPostArgs" finished-at="2017-12-16T13:37:15Z" duration-ms="266" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostArgs -->
        <test-method signature="testPostDefaultBodyResponse()[pri:0, instance:Httpbin.HttpBinStatusCodeTest@2e005c4b]" started-at="2017-12-16T13:37:15Z" name="testPostDefaultBodyResponse" finished-at="2017-12-16T13:37:15Z" duration-ms="136" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[Header - Server] expected:
<'nginx'>
 but was:
<'meinheld/0.6.1'>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [Header - Server] expected:
<'nginx'>
 but was:
<'meinheld/0.6.1'>
	at Httpbin.HttpBinStatusCodeTest.testPostDefaultBodyResponse(HttpBinStatusCodeTest.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostDefaultBodyResponse -->
        <test-method signature="testPostInvalidMethod()[pri:0, instance:Httpbin.HttpBinStatusCodeTest@2e005c4b]" started-at="2017-12-16T13:37:15Z" name="testPostInvalidMethod" finished-at="2017-12-16T13:37:15Z" duration-ms="136" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostInvalidMethod -->
        <test-method signature="testPostJson1()[pri:0, instance:Httpbin.HttpBinStatusCodeTest@2e005c4b]" started-at="2017-12-16T13:37:15Z" name="testPostJson1" finished-at="2017-12-16T13:37:15Z" duration-ms="267" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostJson1 -->
        <test-method signature="testPostJson2()[pri:0, instance:Httpbin.HttpBinStatusCodeTest@2e005c4b]" started-at="2017-12-16T13:37:15Z" name="testPostJson2" finished-at="2017-12-16T13:37:15Z" duration-ms="136" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostJson2 -->
        <test-method signature="testPostJson3()[pri:0, instance:Httpbin.HttpBinStatusCodeTest@2e005c4b]" started-at="2017-12-16T13:37:15Z" name="testPostJson3" finished-at="2017-12-16T13:37:15Z" duration-ms="136" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostJson3 -->
      </class> <!-- Httpbin.HttpBinStatusCodeTest -->
      <class name="Httpbin.HttpBinHeadersTest">
        <test-method signature="testGetArgs1()[pri:0, instance:Httpbin.HttpBinHeadersTest@6e20b53a]" started-at="2017-12-16T13:37:12Z" name="testGetArgs1" finished-at="2017-12-16T13:37:13Z" duration-ms="690" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[JSON body args] expected:
<'{"hello1":"world1","hello2":"world2"}'>
 but was:
<'{}'>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [JSON body args] expected:
<'{"hello1":"world1","hello2":"world2"}'>
 but was:
<'{}'>
	at Httpbin.HttpBinHeadersTest.testGetArgs1(HttpBinHeadersTest.java:130)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetArgs1 -->
        <test-method signature="testGetArgs2()[pri:0, instance:Httpbin.HttpBinHeadersTest@6e20b53a]" started-at="2017-12-16T13:37:13Z" name="testGetArgs2" finished-at="2017-12-16T13:37:13Z" duration-ms="141" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[JSON body args] expected:
<'{"hello1":"world1","hello2":"world1"}'>
 but was:
<'{}'>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [JSON body args] expected:
<'{"hello1":"world1","hello2":"world1"}'>
 but was:
<'{}'>
	at Httpbin.HttpBinHeadersTest.testGetArgs2(HttpBinHeadersTest.java:161)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetArgs2 -->
        <test-method signature="testGetArgs3()[pri:0, instance:Httpbin.HttpBinHeadersTest@6e20b53a]" started-at="2017-12-16T13:37:13Z" name="testGetArgs3" finished-at="2017-12-16T13:37:13Z" duration-ms="140" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[JSON body args] expected:
<'{"hello1":["world1","world2"]}'>
 but was:
<'{}'>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [JSON body args] expected:
<'{"hello1":["world1","world2"]}'>
 but was:
<'{}'>
	at Httpbin.HttpBinHeadersTest.testGetArgs3(HttpBinHeadersTest.java:181)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetArgs3 -->
        <test-method signature="testGetArgs4()[pri:0, instance:Httpbin.HttpBinHeadersTest@6e20b53a]" started-at="2017-12-16T13:37:13Z" name="testGetArgs4" finished-at="2017-12-16T13:37:14Z" duration-ms="144" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[JSON body args] expected:
<'{"hello1":["world1","world1"]}'>
 but was:
<'{}'>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [JSON body args] expected:
<'{"hello1":["world1","world1"]}'>
 but was:
<'{}'>
	at Httpbin.HttpBinHeadersTest.testGetArgs4(HttpBinHeadersTest.java:201)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetArgs4 -->
        <test-method signature="testGetDefaultBodyResponse()[pri:0, instance:Httpbin.HttpBinHeadersTest@6e20b53a]" started-at="2017-12-16T13:37:14Z" name="testGetDefaultBodyResponse" finished-at="2017-12-16T13:37:14Z" duration-ms="147" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[[Header - Server] expected:
<'nginx'>
 but was:
<'meinheld/0.6.1'>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: [Header - Server] expected:
<'nginx'>
 but was:
<'meinheld/0.6.1'>
	at Httpbin.HttpBinHeadersTest.testGetDefaultBodyResponse(HttpBinHeadersTest.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetDefaultBodyResponse -->
        <test-method signature="testGetHeaders()[pri:0, instance:Httpbin.HttpBinHeadersTest@6e20b53a]" started-at="2017-12-16T13:37:14Z" name="testGetHeaders" finished-at="2017-12-16T13:37:14Z" duration-ms="143" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetHeaders -->
        <test-method signature="testGetInvalidMethod()[pri:0, instance:Httpbin.HttpBinHeadersTest@6e20b53a]" started-at="2017-12-16T13:37:14Z" name="testGetInvalidMethod" finished-at="2017-12-16T13:37:14Z" duration-ms="158" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetInvalidMethod -->
        <test-method signature="testGetInvalidUrl()[pri:0, instance:Httpbin.HttpBinHeadersTest@6e20b53a]" started-at="2017-12-16T13:37:14Z" name="testGetInvalidUrl" finished-at="2017-12-16T13:37:14Z" duration-ms="266" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetInvalidUrl -->
      </class> <!-- Httpbin.HttpBinHeadersTest -->
    </test> <!-- Sequential tests -->
  </suite> <!-- Sequential -->
</testng-results>
