<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Няша" failures="0" tests="6" name="Httpbin.HttpBinStatusCodeTest" time="1.077" errors="1" timestamp="16 Dec 2017 10:37:16 GMT">
  <testcase classname="Httpbin.HttpBinStatusCodeTest" name="testPostInvalidMethod" time="0.136"/>
  <testcase classname="Httpbin.HttpBinStatusCodeTest" name="testPostDefaultBodyResponse" time="0.136">
    <error message="[Header - Server] expected:
&lt;&#039;nginx&#039;&gt;
 but was:
&lt;&#039;meinheld/0.6.1&#039;&gt;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: [Header - Server] expected:
<'nginx'>
 but was:
<'meinheld/0.6.1'>
	at Httpbin.HttpBinStatusCodeTest.testPostDefaultBodyResponse(HttpBinStatusCodeTest.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- testPostDefaultBodyResponse -->
  <testcase classname="Httpbin.HttpBinStatusCodeTest" name="testPostArgs" time="0.266"/>
  <testcase classname="Httpbin.HttpBinStatusCodeTest" name="testPostJson2" time="0.136"/>
  <testcase classname="Httpbin.HttpBinStatusCodeTest" name="testPostJson1" time="0.267"/>
  <testcase classname="Httpbin.HttpBinStatusCodeTest" name="testPostJson3" time="0.136"/>
</testsuite> <!-- Httpbin.HttpBinStatusCodeTest -->
